### ISSUE TITLE
ImportError: cannot import name InlineProcessor

### ISSUE THREAD

**Issue by alexpapworth** [facelessuser/MarkdownPreview#111]
Hiya. Seeing this error when running the package on Sublime today.

```python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "/Users/alexpapworth/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 1075, in run
  File "/Users/alexpapworth/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 547, in run
  File "/Users/alexpapworth/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 488, in convert_markdown
  File "/Users/alexpapworth/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 412, in postprocessor_pathconverter
  File "/Users/alexpapworth/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/pathconverter.py", line 39, in <module>
    from . import util
  File "/Users/alexpapworth/Library/Application Support/Sublime Text 3/Packages/pymdownx/st3/pymdownx/util.py", line 9, in <module>
    from markdown.inlinepatterns import InlineProcessor, util
ImportError: cannot import name InlineProcessor
```

I tried removing and installing the package again for sanity, but got the same error.

Can I provide any more details to help?

**Comment by alexpapworth** [comment]
Ah, nevermind, looks like it's related to this issue. https://github.com/facelessuser/MarkdownPreview/issues/99

Restarting Sublime fixed it.

**Comment by facelessuser** [comment]
Yep, I was just about to respond. While dependencies and packages often get updated at the same time, that doesn't mean they get reloaded correctly, and old, already imported versions may persist in memory. Restarting is advised when after an update there seems to be issues.
