### ISSUE TITLE
ImportError: cannot import name InlineProcessor

### ISSUE THREAD

**Issue by benkoller** [facelessuser/MarkdownPreview#99]
Hi,

whenever I try to start the preview or build HTML from my markdowns I receive a `ImportError: cannot import name InlineProcessor`. The error occurs for all markdown parsers (gitlab, github, markdown). It seems to be an issue in the interplay with pymdownx, as the ImportError is thrown there.

I'm running on OSX 10.14.6 with Sublime Text 3.2.2, Build 3211.

Cheers,
Ben

**Comment by facelessuser** [comment]
You may need to run the package control command `satisfy dependencies`, make sure they update appropriately, and restart Sublime to make sure everything loads appropriately.

If after that, you still aren't working, I'm going to need more details, such as: pymdownx version, Markdown version, etc.

@gir-bot add S: needs-confirmation
@gir-bot remove S: triage

**Comment by benkoller** [comment]
Thanks for that. Embarrassingly I tried a couple of things but never considered satisfying dependencies and restarting ST before creating the ticket. Your patience and helpful response is much appreciated.

**Comment by facelessuser** [comment]
Yeah, unfortunately dependency upgrades are not always the smoothest in Sublime. To some degree I expect some issues like this when I explicitly require newer dependencies in a release.

**Comment by chinskiy** [comment]
Hello
Also got this error after a fresh installation. `satisfy dependencies` in ST helps.

Think that if it cannot be fixed it would be good to add to the `common issues` section in docs or note on the installation page.

**Comment by JohnEmhoff** [comment]
I'm getting this error even after running `satisfy dependencies`:

```
Package Control: All dependencies have been satisfied
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "/home/john/.config/sublime-text-3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 1075, in run
  File "/home/john/.config/sublime-text-3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 547, in run
  File "/home/john/.config/sublime-text-3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 488, in convert_markdown
  File "/home/john/.config/sublime-text-3/Installed Packages/MarkdownPreview.sublime-package/markdown_preview.py", line 412, in postprocessor_pathconverter
  File "/home/john/.config/sublime-text-3/Packages/pymdownx/st3/pymdownx/pathconverter.py", line 38, in <module>
    from . import util
  File "/home/john/.config/sublime-text-3/Packages/pymdownx/st3/pymdownx/util.py", line 8, in <module>
    from markdown.inlinepatterns import InlineProcessor
ImportError: cannot import name InlineProcessor
```

**Comment by facelessuser** [comment]
Hmm, I am not seeing this issue. But Maybe I need to check on ST3 as I've run it on ST4 beta.

**Comment by facelessuser** [comment]
Runs fine on ST3, try deleting both `pymdownx` and `markdown` from your Sublime `Packages` folder, then run `Satisfy Dependencies` again, and restart afterward. That should fix it.
